### ISSUE TITLE
Remove all usage of ObjectManager

### ISSUE THREAD

**Issue by tomasnorre** [tomasnorre/crawler#980]

**Comment by tomasnorre** [comment]
No occurrences found anymore.

**Comment by cweiske** [comment]
Fixed with #925.

**Comment by tomasnorre** [comment]
Hi, 

I don't quite understand what you mean. Should this PR be reverted? The message updated.
Sorry I'm a little confused.

**Comment by cweiske** [comment]
No, the PR should not be reverted.

My comment was about 2 things:
1. It links the commit/pr which fixed this issue, because this was not obvious.
2. A note that the crawler 11.x branch does not contain this patch, and why. For other users who may stumble about this issue when they upgrade their TYPO3 instances.

**Comment by tomasnorre** [comment]
Thanks for clarifying this. I was a little confused as it didn't see it being merged :)
